@startuml

title __JAVA_ASSIGNMENT's Class Diagram__\n

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.Cart {
        ~ cartQuantity : int
        ~ cartUser : String
        + Cart()
        + Cart()
        + getCartProduct()
        + getCartQuantity()
        + getCartUser()
        + setCartProduct()
        + setCartQuantity()
        + setCartUser()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    interface com.java.JAVA_ASSIGNMENT.CartDao {
        {abstract} + addCart()
        {abstract} + deleteCart()
        {abstract} + getCart()
        {abstract} + updateCart()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.CartDaoImp {
        {static} + userCartDatabase : ArrayList<Cart>
        + addCart()
        + deleteCart()
        + getCart()
        + updateCart()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.Customer {
        ~ firstTimeLogin : boolean
        - address : String
        - paymentPassword : String
        + Customer()
        + Customer()
        + Customer()
        + getAddress()
        + getPaymentPassword()
        + getUserWallet()
        + setAddress()
        + setPaymentPassword()
        + setUserWallet()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    interface com.java.JAVA_ASSIGNMENT.CustomerDao {
        {abstract} + deleteCustomer()
        {abstract} + getCustomer()
        {abstract} + loginCustomer()
        {abstract} + registerCustomer()
        {abstract} + updateCustomer()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.CustomerDaoImp {
        {static} + customerDatabase : ArrayList<Customer>
        + deleteCustomer()
        + getCustomer()
        + loginCustomer()
        + registerCustomer()
        + updateCustomer()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.DatabaseHandler {
        {static} + main()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.Favorites {
        ~ favoritesUser : String
        + Favorites()
        + Favorites()
        + getFavoritesProduct()
        + getFavoritesUser()
        + setFavoritesProduct()
        + setFavoritesUser()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    interface com.java.JAVA_ASSIGNMENT.FavoritesDao {
        {abstract} + addFavorites()
        {abstract} + deleteFavorites()
        {abstract} + getFavorites()
        {abstract} + updateFavorites()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.FavoritesDaoImp {
        {static} + userFavoritesDatabase : ArrayList<Favorites>
        + addFavorites()
        + deleteFavorites()
        + getFavorites()
        + updateFavorites()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.Feedback {
        ~ feedbackCommentBySeller : String
        ~ feedbackCustomerName : String
        ~ feedbackID : String
        ~ feedbackRating : int
        ~ feedbackReview : String
        + Feedback()
        + Feedback()
        + getFeedbackCommentBySeller()
        + getFeedbackCustomerName()
        + getFeedbackID()
        + getFeedbackProduct()
        + getFeedbackRating()
        + getFeedbackReview()
        + setFeedbackCommentBySeller()
        + setFeedbackCustomerName()
        + setFeedbackID()
        + setFeedbackProduct()
        + setFeedbackRating()
        + setFeedbackReview()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    interface com.java.JAVA_ASSIGNMENT.FeedbackDao {
        {abstract} + addFeedback()
        {abstract} + deleteFeedback()
        {abstract} + getFeedback()
        {abstract} + updateFeedback()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.FeedbackDaoImp {
        {static} + feedbackDataBase : ArrayList<Feedback>
        + addFeedback()
        + deleteFeedback()
        + getFeedback()
        + updateFeedback()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.Main {
        {static} + input : Scanner
        {static} + sessionCustomer : Customer
        {static} + sessionSeller : Seller
        {static} + cartPage()
        {static} + categoryPage()
        {static} + checkoutPage()
        {static} + exitApp()
        {static} + favoritesPage()
        {static} + feedbackPage()
        {static} + homePage()
        {static} + logOutPage()
        {static} + loginPage()
        {static} + main()
        {static} + mainMenuPage()
        {static} + manageFeedbackPage()
        {static} + manageOrdersPage()
        {static} + managePaymentPage()
        {static} + manageProductPage()
        {static} + manageSellerProfilePage()
        {static} + orderHistoryPage()
        {static} + productDisplayPage()
        {static} + registerPage()
        {static} + searchPage()
        {static} + sellerDashboardPage()
        {static} + userProfilePage()
        {static} + walletPage()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.Notification {
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    interface com.java.JAVA_ASSIGNMENT.NotificationDao {
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.NotificationDaoImp {
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    interface com.java.JAVA_ASSIGNMENT.OrderDao {
        {abstract} + addOrders()
        {abstract} + deleteOrders()
        {abstract} + getOrders()
        {abstract} + updateOrders()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.Orders {
        ~ orderCart : ArrayList<Cart>
        ~ orderCustomerName : String
        ~ orderDate : Date
        ~ orderID : String
        ~ orderRatedOrNot : String
        ~ orderReceivedOrNot : String
        ~ orderSellerUsername : String
        ~ orderStatus : String
        ~ orderTotalPaid : double
        ~ orderTrackingID : String
        + Orders()
        + Orders()
        + getOrderCart()
        + getOrderCustomer()
        + getOrderCustomerName()
        + getOrderDate()
        + getOrderID()
        + getOrderRatedOrNot()
        + getOrderReceivedOrNot()
        + getOrderSellerUsername()
        + getOrderStatus()
        + getOrderTotalPaid()
        + getOrderTrackingID()
        + setOrderCart()
        + setOrderCustomer()
        + setOrderCustomerName()
        + setOrderDate()
        + setOrderID()
        + setOrderRatedOrNot()
        + setOrderReceivedOrNot()
        + setOrderSellerUsername()
        + setOrderStatus()
        + setOrderTotalPaid()
        + setOrderTrackingID()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.OrdersDaoImp {
        {static} + orderDatabase : ArrayList<Orders>
        + addOrders()
        + deleteOrders()
        + getOrders()
        + updateOrders()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.Product {
        - productCategory : String
        - productDescription : String
        - productID : String
        - productName : String
        - productPrice : double
        - productSalesCount : int
        - productSellerUsername : String
        - productStockCount : int
        + Product()
        + Product()
        + Product()
        + getProductCategory()
        + getProductDescription()
        + getProductID()
        + getProductName()
        + getProductPrice()
        + getProductSalesCount()
        + getProductSellerUsername()
        + getProductStockCount()
        + setProductCategory()
        + setProductDescription()
        + setProductID()
        + setProductName()
        + setProductPrice()
        + setProductSalesCount()
        + setProductSellerUsername()
        + setProductStockCount()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    interface com.java.JAVA_ASSIGNMENT.ProductDao {
        {abstract} + addProduct()
        {abstract} + deleteProduct()
        {abstract} + getProduct()
        {abstract} + getTop3SellingProduct()
        {abstract} + updateProduct()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.ProductDaoImp {
        {static} + productDatabase : ArrayList<Product>
        + addProduct()
        + deleteProduct()
        + getProduct()
        + getTop3SellingProduct()
        + updateProduct()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.Seller {
        - sellerProfit : double
        - sellerUsername : String
        + getSellerProfit()
        + getSellerUsername()
        + setSellerProfit()
        + setSellerUsername()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    interface com.java.JAVA_ASSIGNMENT.SellerDao {
        {abstract} + deleteSeller()
        {abstract} + getSeller()
        {abstract} + loginSeller()
        {abstract} + registerSeller()
        {abstract} + updateSeller()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.SellerDaoImp {
        {static} + sellerDatabase : ArrayList<Seller>
        + deleteSeller()
        + getSeller()
        + loginSeller()
        + registerSeller()
        + updateSeller()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.User {
        - email : String
        - firstName : String
        - lastName : String
        - password : String
        - username : String
        + getEmail()
        + getFirstName()
        + getLastName()
        + getPassword()
        + getUsername()
        + setEmail()
        + setFirstName()
        + setLastName()
        + setPassword()
        + setUsername()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.Wallet {
        ~ userWalletTransaction : ArrayList<WalletTransaction>
        ~ walletBalance : double
        + Wallet()
        + addWalletTransaction()
        + getWalletBalance()
        + getWalletTransaction()
        + setWalletBalance()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    interface com.java.JAVA_ASSIGNMENT.WalletDao {
        {abstract} + topUpWalletBalance()
        {abstract} + updateWalletBalance()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.WalletDaoImp {
        + topUpWalletBalance()
        + updateWalletBalance()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.WalletTransaction {
        ~ transactionAmount : double
        ~ transactionDateTime : Date
        ~ transactionID : String
        ~ transactionOrderID : String
        ~ transactionSellerName : String
        + WalletTransaction()
        + WalletTransaction()
        + getTransactionAmount()
        + getTransactionDateTime()
        + getTransactionID()
        + getTransactionOrderID()
        + getTransactionSellerName()
        + setTransactionAmount()
        + setTransactionDateTime()
        + setTransactionID()
        + setTransactionOrderID()
        + setTransactionSellerName()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    interface com.java.JAVA_ASSIGNMENT.WalletTransactionDao {
        {abstract} + addWalletTransaction()
        {abstract} + getWalletTransaction()
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.WalletTransactionDaoImp {
        + addWalletTransaction()
        + getWalletTransaction()
    }
  }
  

  com.java.JAVA_ASSIGNMENT.Cart o-- com.java.JAVA_ASSIGNMENT.Product : cartProduct
  com.java.JAVA_ASSIGNMENT.CartDaoImp .up.|> com.java.JAVA_ASSIGNMENT.CartDao
  com.java.JAVA_ASSIGNMENT.Customer -up-|> com.java.JAVA_ASSIGNMENT.User
  com.java.JAVA_ASSIGNMENT.Customer o-- com.java.JAVA_ASSIGNMENT.Wallet : userWallet
  com.java.JAVA_ASSIGNMENT.CustomerDaoImp .up.|> com.java.JAVA_ASSIGNMENT.CustomerDao
  com.java.JAVA_ASSIGNMENT.Favorites o-- com.java.JAVA_ASSIGNMENT.Product : favoritesProduct
  com.java.JAVA_ASSIGNMENT.FavoritesDaoImp .up.|> com.java.JAVA_ASSIGNMENT.FavoritesDao
  com.java.JAVA_ASSIGNMENT.Feedback o-- com.java.JAVA_ASSIGNMENT.Product : feedbackProduct
  com.java.JAVA_ASSIGNMENT.FeedbackDaoImp .up.|> com.java.JAVA_ASSIGNMENT.FeedbackDao
  com.java.JAVA_ASSIGNMENT.NotificationDaoImp .up.|> com.java.JAVA_ASSIGNMENT.NotificationDao
  com.java.JAVA_ASSIGNMENT.OrdersDaoImp .up.|> com.java.JAVA_ASSIGNMENT.OrderDao
  com.java.JAVA_ASSIGNMENT.ProductDaoImp .up.|> com.java.JAVA_ASSIGNMENT.ProductDao
  com.java.JAVA_ASSIGNMENT.Seller -up-|> com.java.JAVA_ASSIGNMENT.User
  com.java.JAVA_ASSIGNMENT.SellerDaoImp .up.|> com.java.JAVA_ASSIGNMENT.SellerDao
  com.java.JAVA_ASSIGNMENT.WalletDaoImp .up.|> com.java.JAVA_ASSIGNMENT.WalletDao
  com.java.JAVA_ASSIGNMENT.WalletTransactionDaoImp .up.|> com.java.JAVA_ASSIGNMENT.WalletTransactionDao


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
