@startuml

title __OMAZON's Class Diagram__\n

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.Cart {
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.Customer {
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.DatabaseHandler {
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.Favorites {
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.Feedback {
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.Main {
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.Notification {
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.Orders {
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.Product {
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.Seller {
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.User {
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.UserHandler {
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.Wallet {
    }
  }
  

  namespace com.java.JAVA_ASSIGNMENT {
    class com.java.JAVA_ASSIGNMENT.WalletTransaction {
    }
  }
  

  com.java.JAVA_ASSIGNMENT.Cart o-- com.java.JAVA_ASSIGNMENT.Product : cartProduct
  com.java.JAVA_ASSIGNMENT.Customer -up-|> com.java.JAVA_ASSIGNMENT.User
  com.java.JAVA_ASSIGNMENT.Customer o-- com.java.JAVA_ASSIGNMENT.Wallet : userWallet
  com.java.JAVA_ASSIGNMENT.Favorites o-- com.java.JAVA_ASSIGNMENT.Product : favoritesProduct
  com.java.JAVA_ASSIGNMENT.Feedback o-- com.java.JAVA_ASSIGNMENT.Product : feedbackProduct
  com.java.JAVA_ASSIGNMENT.Seller -up-|> com.java.JAVA_ASSIGNMENT.User


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
